[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pigeon = "8BThYttJrWRaQYwZmYkZiHQrE5nLaGYCS5mWXapyEEoa"

[programs.devnet]
pigeon_cctp = "Anchor1111111111111111111111111111111111111111"

[programs.mainnet]
pigeon_cctp = "Anchor1111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
